 const instrumentNames = [
    "-",
    "Drums",
    "Djembe",
    "Electric Guitar",
    "Acoustic Guitar",
    "Bass Guitar",
    "Keyboard",
    "Synthesizer",
    "Grand Piano",
    "Accordion",
    "Vocal",
    "Microphone",
    "Harmonica",
    "Trumpet",
    "Trombone",
    "French Horn",
    "Tuba",
    "Saxophone",
    "Clarinet",
    "Flute",
    "Violin",
    "Cello",
    "Double Bass",
    "Recorder",
    "Streamer",
    "Listener",
    "Guitar Vocal",
    "Keyboard Vocal",
    "Bodhran",
    "Bassoon",
    "Oboe",
    "Harp",
    "Viola",
    "Congas",
    "Bongo",
    "Vocal Bass",
    "Vocal Tenor",
    "Vocal Alto",
    "Vocal Soprano",
    "Banjo",
    "Mandolin",
    "Ukulele",
    "Bass Ukulele",
    "Vocal Baritone",
    "Vocal Lead",
    "Mountain Dulcimer",
    "Scratching",
    "Rapping",
    "Vibraphone",
    "Conductor",
  ];
 const instrumentImages = [
    "", // "none.png",
    "drumset.png",
    "djembe.png",
    "eguitar.png",
    "aguitar.png",
    "bassguitar.png",
    "https://im.dt.in.th/ipfs/bafybeiht32hd6smodhvlh62j4mei3zy4qyfmi67gvayl5u6q5rk7cbmfmi/keyboard.webp",
    "synthesizer.png",
    "grandpiano.png",
    "accordeon.png",
    "vocal.png",
    "microphone.png",
    "harmonica.png",
    "trumpet.png",
    "trombone.png",
    "frenchhorn.png",
    "tuba.png",
    "saxophone.png",
    "clarinet.png",
    "flute.png",
    "violin.png",
    "cello.png",
    "doublebass.png",
    "recorder.png",
    "streamer.png",
    "listener.png",
    "guitarvocal.png",
    "keyboardvocal.png",
    "bodhran.png",
    "bassoon.png",
    "oboe.png",
    "harp.png",
    "viola.png",
    "congas.png",
    "bongo.png",
    "vocalbass.png",
    "vocaltenor.png",
    "vocalalto.png",
    "vocalsoprano.png",
    "banjo.png",
    "mandolin.png",
    "ukulele.png",
    "bassukulele.png",
    "vocalbaritone.png",
    "vocallead.png",
    "mountaindulcimer.png",
    "scratching.png",
    "rapping.png",
    "vibraphone.png",
    "conductor.png",
  ];
 const instrumentImageBase =
    "https://cdn.jsdelivr.net/gh/jamulussoftware/jamulus@r3_9_1/src/res/instruments/";
    export function getInstrumentImageUrl(instrumentName: string) {
    const imageIndex = instrumentNames.indexOf(instrumentName);
    const image = instrumentImages[imageIndex];
    const imageUrl = image
        ? `${new URL(image, instrumentImageBase)}`
        : undefined;
    return imageUrl;
}

